apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-node-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Megs17/FORTSTAK_TASK.git
    targetRevision: main
    path: manifests
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
