apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: 257034520231.dkr.ecr.us-east-1.amazonaws.com/todo-list-nodejs:f1f4aca480a77b10104cbff1e6b7b816c70ddb2e
        ports:
        - containerPort: 4000
        env:
        - name: mongoDbUrl
          value: mongodb://mongo-0.mongo:27017/todolistDb